-- ************************** SqlDBM: Databricks **************************
-- * Generated by SqlDBM: abe-sqldbmdb by abraham.pabbathi@databricks.com *


-- * The 'delta.columnMapping.mode' property is added by default to make the alter script work correctly *

-- ************************************** stg_pets

CREATE TABLE stg_pets
(
 pet_name      string NOT NULL,
 birth_date    date NOT NULL COMMENT 'birth date of the pet',
 adoption_time timestamp NOT NULL,
 weight        float NOT NULL
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');


-- ************************************** test_schema.stg_pets

CREATE TABLE test_schema.stg_pets
(
 pet_name      string NOT NULL,
 birth_date    date NOT NULL,
 adoption_time timestamp NOT NULL,
 weight        float NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 5, delta.minReaderVersion = 2, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.columnMapping.mode = 'name');


-- ************************************** raw_pets

CREATE TABLE raw_pets
(
 pet_name string NOT NULL
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');


-- ************************************** persons

CREATE TABLE persons
(
 first_name string NOT NULL,
 last_name  string NOT NULL,
 nickname   string NOT NULL,
 CONSTRAINT PK_2 PRIMARY KEY (first_name, last_name)
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');


-- ************************************** test_schema.customers

CREATE TABLE test_schema.customers
(
 CustomerKey          int,
 GeographyKey         int,
 CustomerAlternateKey string,
 Title                string,
 FirstName            string,
 MiddleName           string,
 LastName             string,
 NameStyle            int,
 BirthDate            date,
 MaritalStatus        string,
 Suffix               string,
 Gender               string,
 EmailAddress         string,
 YearlyIncome         double,
 TotalChildren        int,
 NumberChildrenAtHome int,
 EnglishEducation     string,
 SpanishEducation     string,
 FrenchEducation      string,
 EnglishOccupation    string,
 SpanishOccupation    string,
 FrenchOccupation     string,
 HouseOwnerFlag       int,
 NumberCarsOwned      int,
 AddressLine1         string,
 AddressLine2         string,
 Phone                string,
 DateFirstPurchase    date,
 CommuteDistance      string
)
USING DELTA
 TBLPROPERTIES (delta.minReaderVersion = 1, delta.minWriterVersion = 2, delta.columnMapping.mode = 'name');


-- ************************************** pets

CREATE TABLE pets
(
 name             string NOT NULL CONSTRAINT PK_1 PRIMARY KEY,
 owner_first_name string NOT NULL,
 owner_last_name  string NOT NULL,
 CONSTRAINT FK_1 FOREIGN KEY (owner_first_name, owner_last_name) REFERENCES persons (first_name, last_name)
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');

